// Code generated by MockGen. DO NOT EDIT.
// Source: internal/app/validators/user-validator.go

// Package mocks is a generated GoMock package.
package mocks

import (
	models "khodza/rest-api/internal/app/models"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockUserValidatorInterface is a mock of UserValidatorInterface interface.
type MockUserValidatorInterface struct {
	ctrl     *gomock.Controller
	recorder *MockUserValidatorInterfaceMockRecorder
}

// MockUserValidatorInterfaceMockRecorder is the mock recorder for MockUserValidatorInterface.
type MockUserValidatorInterfaceMockRecorder struct {
	mock *MockUserValidatorInterface
}

// NewMockUserValidatorInterface creates a new mock instance.
func NewMockUserValidatorInterface(ctrl *gomock.Controller) *MockUserValidatorInterface {
	mock := &MockUserValidatorInterface{ctrl: ctrl}
	mock.recorder = &MockUserValidatorInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserValidatorInterface) EXPECT() *MockUserValidatorInterfaceMockRecorder {
	return m.recorder
}

// ValidateUserCreate mocks base method.
func (m *MockUserValidatorInterface) ValidateUserCreate(user *models.User) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ValidateUserCreate", user)
	ret0, _ := ret[0].(error)
	return ret0
}

// ValidateUserCreate indicates an expected call of ValidateUserCreate.
func (mr *MockUserValidatorInterfaceMockRecorder) ValidateUserCreate(user interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ValidateUserCreate", reflect.TypeOf((*MockUserValidatorInterface)(nil).ValidateUserCreate), user)
}

// ValidateUserUpdate mocks base method.
func (m *MockUserValidatorInterface) ValidateUserUpdate(user *models.User) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ValidateUserUpdate", user)
	ret0, _ := ret[0].(error)
	return ret0
}

// ValidateUserUpdate indicates an expected call of ValidateUserUpdate.
func (mr *MockUserValidatorInterfaceMockRecorder) ValidateUserUpdate(user interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ValidateUserUpdate", reflect.TypeOf((*MockUserValidatorInterface)(nil).ValidateUserUpdate), user)
}
